Reprise globale du package

diff --git a/scripts/backup b/scripts/backup
--- a/scripts/backup
+++ b/scripts/backup
@@ -1,29 +1,63 @@
 #!/bin/bash
 
-# The parameter $1 is the backup directory location dedicated to the app
-backup_dir=$1
+#=================================================
+# GENERIC STARTING
+#=================================================
+# MANAGE FAILURE OF THE SCRIPT
+#=================================================
 
-# The parameter $2 is theid of the app instance
-app=$2
+# Exit on command errors and treat unset variables as an error
+set -eu
 
-# Source app helpers
+#=================================================
+# IMPORT GENERIC HELPERS
+#=================================================
+
+if [ ! -e .fonctions ]; then
+	# Rapatrie le fichier de fonctions si il n'est pas dans le dossier courant
+	sudo cp ../settings/scripts/.fonctions ./.fonctions
+	sudo chmod a+rx .fonctions
+fi
+source .fonctions
 source /usr/share/yunohost/helpers
+
+#=================================================
+# LOAD SETTINGS
+#=================================================
+
+app=$YNH_APP_INSTANCE_NAME
 
 domain=$(ynh_app_setting_get $app domain)
 final_path=$(ynh_app_setting_get $app final_path)
+db_name=$(ynh_app_setting_get $app db_name)
+db_pwd=$(ynh_app_setting_get "$app" mysqlpwd)
 
-# Copy the app files
-sudo mkdir -p ${backup_dir}/var/www
-sudo cp -a $final_path "${backup_dir}/var/www/$app"
+#=================================================
+# STANDARD BACKUP STEPS
+#=================================================
+# BACKUP OF THE MAIN DIR OF THE APP
+#=================================================
 
-# Copy the conf files
-sudo mkdir -p "${backup_dir}/conf"
-sudo cp -a /etc/nginx/conf.d/$domain.d/$app.conf "${backup_dir}/conf/nginx.conf"
+CHECK_SIZE "$final_path"
+ynh_backup "$final_path" "sources"
 
-# Copy dedicated php-fpm process to backup folder
-sudo cp -a /etc/php5/fpm/pool.d/$app.conf "${backup_dir}/conf/php-fpm.conf"
-sudo cp -a /etc/php5/fpm/conf.d/20-$app.ini "${backup_dir}/conf/php-fpm.ini"
+#=================================================
+# BACKUP OF THE NGINX CONFIGURATION
+#=================================================
 
-# Backup db
-root_pwd=$(sudo cat /etc/yunohost/mysql)
-sudo su -c "mysqldump -u root -p$root_pwd --no-create-db $app > ${backup_dir}/db.sql"
+ynh_backup "/etc/nginx/conf.d/$domain.d/$app.conf" "nginx.conf"
+
+#=================================================
+# BACKUP OF THE PHP-FPM CONFIGURATION
+#=================================================
+
+ynh_backup "/etc/php5/fpm/pool.d/$app.conf" "php-fpm.conf"
+ynh_backup "/etc/php5/fpm/conf.d/20-$app.ini" "php-fpm.ini"
+
+#=================================================
+# BACKUP OF THE SQL BDD
+#=================================================
+
+ynh_mysql_dump_db "$db_name" > dump.sql
+CHECK_SIZE "dump.sql"
+ynh_backup "dump.sql" "db.sql"
diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -1,17 +1,27 @@
 #!/bin/bash
 
-source .fonctions	# Charge les fonctions génériques habituellement utilisées dans le script
+#=================================================
+# GENERIC STARTING
+#=================================================
+# IMPORT GENERIC HELPERS
+#=================================================
 
-CLEAN_SETUP () {
-# Nettoyage des résidus d'installation non pris en charge par le script remove.
-	# Clean hosts
-	sudo sed -i '/#WORDPRESS/d' /etc/hosts
-}
-TRAP_ON	# Active trap pour arrêter le script si une erreur est détectée.
+source .fonctions
+source /usr/share/yunohost/helpers
+
+#=================================================
+# MANAGE FAILURE OF THE SCRIPT
+#=================================================
+
+ynh_abort_if_errors	# Active trap pour arrêter le script si une erreur est détectée.
+
+#=================================================
+# RETRIEVE ARGUMENTS FROM THE MANIFEST
+#=================================================
 
 # Retrieve arguments
 domain=$YNH_APP_ARG_DOMAIN
-path=$YNH_APP_ARG_PATH
+path_url=$YNH_APP_ARG_PATH
 admin_wordpress=$YNH_APP_ARG_ADMIN
 language=$YNH_APP_ARG_LANGUAGE
 multisite=$YNH_APP_ARG_MULTISITE
@@ -19,138 +29,168 @@ is_public=$YNH_APP_ARG_IS_PUBLIC
 
 app=$YNH_APP_INSTANCE_NAME
 
-# Source app helpers
-source /usr/share/yunohost/helpers
-
-# Vérifie que les variables ne sont pas vides.
-CHECK_VAR "$app" "app name not set"
-
+#=================================================
+# CHECK IF THE APP CAN BE INSTALLED WITH THIS ARGS
+#=================================================
 
 CHECK_USER "$admin_wordpress"	# Vérifie la validité de l'user admin
-
-CHECK_PATH	# Vérifie et corrige la syntaxe du path.
+path_url=$(ynh_normalize_url_path $path_url)	# Vérifie et corrige la syntaxe du path.
 CHECK_DOMAINPATH	# Vérifie la disponibilité du path et du domaine.
-
 CHECK_FINALPATH	# Vérifie que le dossier de destination n'est pas déjà utilisé.
 
-if [ "$path" == "/" ] && [ "$multisite" = "Yes" ]; then
-    echo "Multisite option of wordpress doesn't work at root of domain." >&2
-	false
+if [ "$path_url" == "/" ] && [ "$multisite" = "Yes" ]; then
+	ynh_die "Multisite option of wordpress doesn't work at root of domain."
 fi
 
-# Enregistre les infos dans la config YunoHost
+#=================================================
+# STORE SETTINGS FROM MANIFEST
+#=================================================
+
 ynh_app_setting_set $app domain $domain
-ynh_app_setting_set $app path $path
+ynh_app_setting_set $app path $path_url
 ynh_app_setting_set $app admin $admin_wordpress
 ynh_app_setting_set $app is_public $is_public
 ynh_app_setting_set $app language $language
 ynh_app_setting_set $app multisite $multisite
 
-GENERATE_DB $app	# Créer une base de données et un utilisateur dédié au nom de l'app.
+#=================================================
+# STANDARD MODIFICATIONS
+#=================================================
+# INSTALL DEPENDENCIES
+#=================================================
 
+ynh_install_app_dependencies php5-cli
 
-# Crée le repertoire de destination et stocke son emplacement.
-sudo mkdir "$final_path"
+#=================================================
+# CREATE A SQL BDD
+#=================================================
+
+db_name=$(ynh_make_valid_dbid $app)
+ynh_app_setting_set $app db_name $db_name
+ynh_mysql_generate_db $db_name $db_name
+
+#=================================================
+# DOWNLOAD, CHECK AND UNPACK SOURCE
+#=================================================
+
 ynh_app_setting_set $app final_path $final_path
+SETUP_SOURCE	# Télécharge la source, décompresse et copie dans $final_path
 
+#=================================================
+# NGINX CONFIGURATION
+#=================================================
 
-SETUP_SOURCE "wordpress.tar.gz"	# Télécharge la source, décompresse et copie dans $final_path
-
-# Et copie le fichier de config nginx
+# Copie le fichier de config nginx
 sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf
-
-
 # Modifie les variables dans le fichier de configuration nginx
-sudo sed -i "s@__PATHTOCHANGE__@$path@g" /etc/nginx/conf.d/$domain.d/$app.conf
+sudo sed -i "s@__PATHTOCHANGE__@$path_url@g" /etc/nginx/conf.d/$domain.d/$app.conf
 sudo sed -i "s@__FINALPATH__@$final_path@g" /etc/nginx/conf.d/$domain.d/$app.conf
 sudo sed -i "s@__NAMETOCHANGE__@$app@g" /etc/nginx/conf.d/$domain.d/$app.conf
 
+#=================================================
+# CREATE DEDICATED USER
+#=================================================
+
+ynh_system_user_create $app	# Créer un utilisateur système dédié à l'app
+
+#=================================================
+# PHP-FPM CONFIGURATION
+#=================================================
+
 POOL_FPM	# Créer le fichier de configuration du pool php-fpm et le configure.
 
+#=================================================
+# SPECIFIC SETUP
+#=================================================
+# CONFIGURE WP-CONFIG
+#=================================================
 
 sudo cp ../conf/wp-config.php $final_path/wp-config.php
-
 # Change variables in Wordpress configuration
-sudo sed -i "s/__DB_USER__/$db_user/g" $final_path/wp-config.php
+sudo sed -i "s/__DB_USER__/$db_name/g" $final_path/wp-config.php
 sudo sed -i "s/__DB_PWD__/$db_pwd/g" $final_path/wp-config.php
 sudo sed -i "s/__DOMAIN__/$domain/g" $final_path/wp-config.php
-sudo sed -i "s@__PATH__@$path@g" $final_path/wp-config.php
-
+sudo sed -i "s@__PATH__@$path_url@g" $final_path/wp-config.php
 
 for i in 1 2 3 4 5 6 7 8
 do
-    j=$(dd if=/dev/urandom bs=1 count=200 2> /dev/null | tr -c -d '[A-Za-z0-9]' | sed -n 's/\(.\{40\}\).*/\1/p')
-    if [ "$j" = "" ];
-    then
-        # For obscure reasons, the loop is too fast at execution
-        sleep 1
-        j=$(dd if=/dev/urandom bs=1 count=200 2> /dev/null | tr -c -d '[A-Za-z0-9]' | sed -n 's/\(.\{40\}\).*/\1/p')
-    fi
-    sudo sed -i "s/KEY$i/$j/g" $final_path/wp-config.php
+	j=$(dd if=/dev/urandom bs=1 count=200 2> /dev/null | tr -c -d '[A-Za-z0-9]' | sed -n 's/\(.\{40\}\).*/\1/p')
+	if [ "$j" = "" ];
+	then
+		# For obscure reasons, the loop is too fast at execution
+		sleep 1
+		j=$(dd if=/dev/urandom bs=1 count=200 2> /dev/null | tr -c -d '[A-Za-z0-9]' | sed -n 's/\(.\{40\}\).*/\1/p')
+	fi
+	sudo sed -i "s/KEY$i/$j/g" $final_path/wp-config.php
 done
 
-# Set permissions to wordpress directory
-sudo chown -R www-data: $final_path
+#=================================================
+# SETTING UP WITH CURL
+#=================================================
 
-# Donne un accès public pour curl
+# Set right permissions for curl install
+sudo chown -R $app: $final_path
+
+# Rend la page d'install publique pour curl
 ynh_app_setting_set $app unprotected_uris "/"
-# Recharge la configuration Nginx
-sudo service nginx reload
-# Régénère la configuration de SSOwat
-sudo yunohost app ssowatconf
+sudo yunohost app ssowatconf	# Régénère la configuration de SSOwat
 
+# Reload Nginx
+sudo systemctl reload nginx
 
 # Wordpress installation
-echo -e "127.0.0.1 $domain #WORDPRESS" | sudo tee -a /etc/hosts
-sleep 1
-curl -kL -H "Host: $domain" --data "&weblog_title=YunoBlog&user_name=$admin_wordpress&admin_password=$db_pwd&admin_password2=$db_pwd&admin_email=$admin_wordpress@$domain&language=$language&Submit=Install+WordPress" https://localhost$path/wp-admin/install.php?step=2 > /dev/null 2>&1
+YNH_CURL "&weblog_title=YunoBlog&user_name=$admin_wordpress&admin_password=$db_pwd&admin_password2=$db_pwd&admin_email=$admin_wordpress@$domain&language=$language&Submit=Install+WordPress" "/wp-admin/install.php?step=2"
 
-echo -n "Please wait during Wordpress installation" >&2
+WARNING echo -n "Please wait during Wordpress installation"
 for i in `seq 1 300`
 do	# La boucle attend la fin de l'installation de wordpress Ou 5 minutes.
-	if mysql --debug-check -u $db_user -p$db_pwd $db_user -e "show tables" | grep -q "wp_options"; then
+	if ynh_mysql_connect_as $db_name $db_pwd $db_name -e "show tables" | grep -q "wp_options"; then
 		break	# Si la table wp_options est trouvée, l'installation de wordpress est terminée. Quitte la boucle.
 	fi
-	echo -n "." >&2
+	WARNING echo -n "."
 	sleep 1
 done
 
+#=================================================
+# LOAD SQL CONFIG
+#=================================================
+
 # Replace variables in sql scripts
-sudo sed -i "s@__DOMAIN_PATH__@$domain$path@g" ../conf/sql/*.sql
+sudo sed -i "s@__DOMAIN_PATH__@$domain$path_url@g" ../conf/sql/*.sql
 sudo sed -i "s/__LANGUAGE__/$language/g" ../conf/sql/*.sql
 sudo sed -i "s/__DATE__/$(date +%s)/g" ../conf/sql/*.sql
 
 # Charge les commandes sql communes à tous les scripts.
-mysql --debug-check -u $db_user -p$db_pwd $db_user < ../conf/sql/common.sql
+# mysql --debug-check -u $db_user -p$db_pwd $db_user < ../conf/sql/common.sql
+ynh_mysql_connect_as $db_name $db_pwd $db_name < ../conf/sql/common.sql
 
-if [ "$multisite" = "Yes" ]
+#=================================================
+# CONFIGURE MULTISITE
+#=================================================
+
+if [ $multisite -eq 1 ]
 then
-	# Installation de php5-cli pour wp-cli
-	sudo apt-get update
-	sudo apt-get install php5-cli -qy
-
-    sudo sed -i "s@#--MULTISITE--@@g" /etc/nginx/conf.d/$domain.d/$app.conf
-    # Autorise le multisite wordpress
-    sudo sed -i "s@//--MULTISITE1--define@define@g" $final_path/wp-config.php
+	sudo sed -i "s@#--MULTISITE--@@g" /etc/nginx/conf.d/$domain.d/$app.conf
+	# Autorise le multisite wordpress
+	sudo sed -i "s@//--MULTISITE1--define@define@g" $final_path/wp-config.php
 
 	# Active le multisite via wp-cli.
 	sudo wget -nv https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar -O $final_path/wp-cli.phar
-  	php $final_path/wp-cli.phar core multisite-convert --path=$final_path --base=$path/ > /dev/null 2>&1
-# 	echo "The 2 warnings of php about \"Permission denied\" on wp-config.php are normal. The install script writing into this file, not wp-cli!"
+	ALL_QUIET php $final_path/wp-cli.phar core multisite-convert --path=$final_path --base=$path_url/
 
-    # Active le multisite wordpress
-    sudo sed -i "s@//--MULTISITE2--define@define@g" $final_path/wp-config.php
+	# Active le multisite wordpress
+	sudo sed -i "s@//--MULTISITE2--define@define@g" $final_path/wp-config.php
 
-    # Charge les commandes sql pour activer les plugins
-    if [ "$is_public" = "No" ];
-    then
+	# Charge les commandes sql pour activer les plugins
+	if [ $is_public -eq 0 ]
+	then
 		sudo sed -i "s@#--PRIVATE--@@g" ../conf/sql/multisite.sql
-    else
+	else
 		sudo sed -i "s@#--PUBLIC--@@g" ../conf/sql/multisite.sql
-    fi
-	mysql --debug-check -u $db_user -p$db_pwd $db_user < ../conf/sql/multisite.sql
+	fi
+	ynh_mysql_connect_as $db_name $db_pwd $db_name < ../conf/sql/multisite.sql
 else
-	if [ "$is_public" = "No" ];
+	if [ $is_public -eq 0 ]
 	then
 		sudo sed -i "s@#--PRIVATE--@@g" /etc/nginx/conf.d/$domain.d/$app.conf
 		sudo sed -i "s@#--PRIVATE--@@g" ../conf/sql/single.sql
@@ -160,32 +200,48 @@ else
 		sudo sed -i "s@#--PUBLIC--@@g" ../conf/sql/single.sql
 	fi
 	# Charge les commandes sql pour activer les plugins
-	mysql --debug-check -u $db_user -p$db_pwd $db_user < ../conf/sql/single.sql
+	ynh_mysql_connect_as $db_name $db_pwd $db_name < ../conf/sql/single.sql
 fi
 
 # Décommente les add_filter, qui auraient provoqué une erreur avec wp-cli
 sudo sed -i "s@//add_filter@add_filter@g" $final_path/wp-config.php
 
+#=================================================
+# STORE THE CHECKSUM OF THE CONFIG FILE
+#=================================================
+
 STORE_MD5_CONFIG "wp-config.php" "$final_path/wp-config.php"	# Enregistre la somme de contrôle du fichier de config
 
+#=================================================
+# GENERIC FINALISATION
+#=================================================
+# SECURING FILES AND DIRECTORIES
+#=================================================
 
-# Configure les droits d'accès au fichiers
-# Les fichiers appartiennent à www-data, pour permettre les mises à jour.
-sudo chown -R www-data: $final_path
+# Les fichiers appartiennent à l'user wordpress, pour permettre les mises à jour.
+sudo chown -R $app: $final_path
 # Sauf le fichier de config wp-config.php qui appartient à root
 sudo chown root: $final_path/wp-config.php
 
-if [ "$is_public" = "No" ];
+#=================================================
+# SETUP SSOWAT
+#=================================================
+
+if [ $is_public -eq 0 ];
 then
 	# Retire l'accès public
 	ynh_app_setting_delete $app unprotected_uris
-	sudo yunohost app ssowatconf
 fi
 
-sudo service nginx reload
+#=================================================
+# RELOAD NGINX
+#=================================================
 
-# Clean hosts
-sudo sed -i '/#WORDPRESS/d' /etc/hosts
+sudo systemctl reload nginx
+
+#=================================================
+# REMOVE WP-CLI.PHAR
+#=================================================
 
 # wp-cli me semble un peu trop permissif... Il a terminé son travail...
 sudo rm -f $final_path/wp-cli.phar
diff --git a/scripts/restore b/scripts/restore
--- a/scripts/restore
+++ b/scripts/restore
@@ -1,60 +1,100 @@
 #!/bin/bash
-# This restore script is adapted to Yunohost >=2.4
 
-# The parameter $1 is the backup directory location dedicated to the app
-backup_dir=$1
+#=================================================
+# GENERIC STARTING
+#=================================================
+# MANAGE FAILURE OF THE SCRIPT
+#=================================================
 
-# The parameter $2 is the id of the app instance ex: ynhexample__2
-app=$2
+# Exit on command errors and treat unset variables as an error
+set -eu
 
-# Source app helpers
+#=================================================
+# IMPORT GENERIC HELPERS
+#=================================================
+
+if [ ! -e .fonctions ]; then
+	# Rapatrie le fichier de fonctions si il n'est pas dans le dossier courant
+	sudo cp ../settings/scripts/.fonctions ./.fonctions
+	sudo chmod a+rx .fonctions
+fi
+source .fonctions
 source /usr/share/yunohost/helpers
 
-# Get old parameter of the app
+#=================================================
+# LOAD SETTINGS
+#=================================================
+
+app=$YNH_APP_INSTANCE_NAME
+
 domain=$(ynh_app_setting_get $app domain)
-path=$(ynh_app_setting_get $app path)
+path_url=$(ynh_app_setting_get $app path)
 is_public=$(ynh_app_setting_get $app is_public)
 final_path=$(ynh_app_setting_get $app final_path)
+db_name=$(ynh_app_setting_get $app db_name)
 
-if [ -d $final_path ]; then
-    ynh_die "There is already a directory: $final_path"
-fi
+#=================================================
+# CHECK IF THE APP CAN BE RESTORED
+#=================================================
+
+sudo yunohost app checkurl "${domain}${path_url}" -a "$app" \
+	|| ynh_die "Path not available: ${domain}${path_url}"
+test ! -d $final_path \
+	|| ynh_die "There is already a directory: $final_path "
+
+#=================================================
+# STANDARD RESTORE STEPS
+#=================================================
+# RESTORE OF THE NGINX CONFIGURATION
+#=================================================
 
 conf=/etc/nginx/conf.d/$domain.d/$app.conf
 if [ -f $conf ]; then
-    ynh_die "There is already a nginx conf file at this path: $conf"
+	ynh_die "There is already a nginx conf file at this path: $conf "
 fi
-# Restore conf files
-sudo cp -a "${backup_dir}/conf/nginx.conf" $conf
+sudo cp -a ./nginx.conf $conf
 
-# Reload Nginx
-sudo service nginx reload
+#=================================================
+# RESTORE OF THE MAIN DIR OF THE APP
+#=================================================
 
-sudo cp -a "${backup_dir}/var/www/$app" $final_path
+sudo cp -a ./sources/. $final_path
+
+#=================================================
+# RESTORE OF THE SQL BDD
+#=================================================
 
 db_pwd=$(ynh_app_setting_get $app mysqlpwd)
-db_user=$app
-ynh_mysql_create_db $db_user $db_user $db_pwd
-sudo su -c "mysql -u $db_user -p$db_pwd $app < ${backup_dir}/db.sql"
-sudo rm -f "${backup_dir}/db.sql"
-sudo sed -i -e "s/'DB_USER', *'[^']*'/'DB_USER', '$app'/g" $final_path/wp-config.php
-sudo sed -i -e "s/'DB_NAME', *'[^']*'/'DB_NAME', '$app'/g" $final_path/wp-config.php
+ynh_mysql_create_db $db_name $db_name $db_pwd
+ynh_mysql_connect_as $db_name $db_pwd $db_name < ./db.sql
 
-# Set permissions
-# Les fichiers appartiennent à www-data, pour permettre les mises à jour.
-sudo chown -R www-data: $final_path
+#=================================================
+# RECREATE OF THE DEDICATED USER
+#=================================================
+
+ynh_system_user_create $app	# Recreate the dedicated user, if not exist
+
+#=================================================
+# RESTORE USER RIGHTS
+#=================================================
+
+# Les fichiers appartiennent à l'user wordpress, pour permettre les mises à jour.
+sudo chown -R $app: $final_path
 # Sauf le fichier de config wp-config.php qui appartient à root
 sudo chown root: $final_path/wp-config.php
 
-# Copy dedicated php-fpm process from backup folder to the right location
-sudo cp -a $backup_dir/conf/php-fpm.conf /etc/php5/fpm/pool.d/$app.conf
-sudo cp -a $backup_dir/conf/php-fpm.ini /etc/php5/fpm/conf.d/20-$app.ini
-# And restart service
-sudo service php5-fpm reload
+#=================================================
+# RESTORE OF THE PHP-FPM CONFIGURATION
+#=================================================
 
-# Set ssowat config
-if [ "$is_public" = "No" ];
-then
-	ynh_app_setting_delete $app skipped_uris
-fi
-sudo yunohost app ssowatconf
+sudo cp -a ./php-fpm.conf /etc/php5/fpm/pool.d/$app.conf
+sudo cp -a ./php-fpm.ini /etc/php5/fpm/conf.d/20-$app.ini
+
+#=================================================
+# GENERIC FINALISATION
+#=================================================
+# RELOAD NGINX AND PHP-FPM
+#=================================================
+
+sudo systemctl reload php5-fpm
+sudo systemctl reload nginx
