trap et maj ynh 2.4

diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -1,19 +1,59 @@
 #!/bin/bash
 
-# Renseigne les variables à partir des arguments.
-domain=$1
-path=$2
-admin_wordpress=$3
-language=$4
-multisite=$5
-is_public=$6
-app=wordpressms
+ynh_version=$(sudo yunohost -v | grep "moulinette:" | cut -d' ' -f2 | cut -d'.' -f1,2)
+# Retrieve arguments
+if [ $ynh_version = "2.4" ]
+then
+	domain=$YNH_APP_ARG_DOMAIN
+	path=$YNH_APP_ARG_PATH
+	admin_wordpress=$YNH_APP_ARG_ADMIN
+	language=$YNH_APP_ARG_LANGUAGE
+	multisite=$YNH_APP_ARG_MULTISITE
+	is_public=$YNH_APP_ARG_IS_PUBLIC
+
+	app=$YNH_APP_INSTANCE_NAME
+
+	# Source app helpers
+	. /usr/share/yunohost/helpers
+else
+	domain=$1
+	path=$2
+	admin_wordpress=$3
+	language=$4
+	multisite=$5
+	is_public=$6
+	app=wordpressms
+fi
+
+
+# Delete files and db if exit with an error
+EXIT_PROPERLY () {
+	trap '' ERR
+	echo -e "\e[91m \e[1m"	# Shell in light red bold
+	echo -e "!!\n  $app install's script has encountered an error. Installation was cancelled.\n!!"
+
+	if [ $ynh_version = "2.2" ]; then
+		/bin/bash ./remove	# Appel le script remove. En 2.2, ce comportement n'est pas automatique.
+	fi
+	exit 1
+}
+TRAP_ON () {	# Activate signal capture
+	trap EXIT_PROPERLY ERR	# Capturing exit signals on error
+}
+TRAP_OFF () {	# Ignoring signal capture until TRAP_ON
+# Pour une raison que j'ignore, la fonction TRAP_ON fonctionne très bien.
+# Mais pas la fonction TRAP_OFF...
+# Utiliser directement `trap '' ERR` dans le code pour l'utiliser, à la place de la fonction.
+	trap '' ERR	# Ignoring exit signals
+}
+TRAP_ON
+
 
 # Vérifie la validité de l'user admin
 sudo yunohost user list --json | grep -q "\"username\": \"$admin_wordpress\""
 if [[ ! $? -eq 0 ]]; then
     echo "Wrong admin"
-    exit 1
+    touch /force_stop
 fi
 
 # Vérifie la présence du / en début de path
@@ -24,7 +64,7 @@ fi
 # Vérifie la disponibilité du path et du domaine.
 sudo yunohost app checkurl $domain$path -a $app
 if [[ ! $? -eq 0 ]]; then
-    exit 1
+    touch /force_stop
 fi
 
 # Vérifie que le dossier de destination n'est pas déjà utilisé.
@@ -32,7 +72,7 @@ final_path=/var/www/$app
 if [ -e "$final_path" ]
 then
     echo "This path already contains a folder"
-    exit 1
+    touch /force_stop
 fi
 
 
@@ -46,11 +86,15 @@ sudo yunohost app setting $app multisite -v $multisite
 
 
 # Génère un mot de passe aléatoire.
-db_pwd=$(cat /dev/urandom | head -n20 | tr -c -d 'A-Za-z0-9' | head -c20)
+db_pwd=$(head -n20 /dev/urandom | tr -c -d 'A-Za-z0-9' | head -c20)
 # Utilise '$app' comme nom d'utilisateur et de base de donnée
 db_user=$app
 # Initialise la base de donnée et stocke le mot de passe mysql.
-sudo yunohost app initdb $db_user -p $db_pwd
+if [ $ynh_version = "2.4" ]; then
+	ynh_mysql_create_db $db_user $db_user $db_pwd
+else
+	sudo yunohost app initdb $db_user -p $db_pwd
+fi
 sudo yunohost app setting $app mysqlpwd -v $db_pwd
 
 
